CREATE TABLE cursos(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(250) NOT NULL,
    categoria ENUM('PROGRAMACIÓN_BÁSICO', 'PROGRAMACIÓN_INTERMEDIO', 'PROGRAMACIÓN_AVANZADO') NOT NULL
);


